version: '2.3'
services:
  bot:
    image: ghcr.io/erisa/watchman
    restart: always
    volumes:
      - type: bind
        source: ./data/Database.db
        target: /app/Database.db
      - type: bind
        source: ./config.json
        target: /app/config.json
